version: "3.9"

services:
  some-service-db:
    image: postgres:15-alpine
    container_name: some-service-db
    environment:
      POSTGRES_DB: some_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped