spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/some_service}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    hikari:
      hikari:
        schema: ${DATABASE_SCHEMA:studios_service}
        maximum-pool-size: 10
        driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate